### ISSUE TITLE
MYSQL_ATTR_SSL_CA

### ISSUE THREAD

**Issue by Aerendir** [Aerendir/bundle-aws-ses-monitor#116]
Explain in the documentation that it is required to add to `config/packages/prod/doctrine.yaml`:

```yaml
doctrine:
    dbal:
        options:
            # http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_MySQL.html#MySQL.Concepts.SSLSupport
            MYSQL_ATTR_SSL_CA: '%kernel.project_dir%/etc/rds-combined-ca-bundle.pem'
```

Used in TrustBack.Me.
