### ISSUE TITLE
Add to Symfony Flex

### ISSUE THREAD

**Issue by Aerendir** [Aerendir/bundle-aws-ses-monitor#23]
https://github.com/symfony/recipes-contrib

- [x] Create a config file in `config/packages/shq_aws_ses_monitor.yaml` with this content:

```yaml
# Aws Ses Monitor
shq_aws_ses_monitor:
    aws_config:
        credentials_service_name: 'Aws\Credentials\Credentials'
        region: '%env(AWS_REGION)%'
    bounces:
        topic:
            name: '%env(AWS_SES_TOPIC_BOUNCES)%'
            endpoint:
                protocol: '%env(APP_SCHEME)%'
                host: '%env(APP_HOST)%'
    complaints:
        topic:
            name: '%env(AWS_SES_TOPIC_COMPLAINTS)%'
            endpoint:
                protocol: '%env(APP_SCHEME)%'
                host: '%env(APP_HOST)%'
    deliveries:
        topic:
            name: '%env(AWS_SES_TOPIC_DELIVERIES)%'
            endpoint:
                protocol: '%env(APP_SCHEME)%'
                host: '%env(APP_HOST)%'
```

- [x] Create a config file in `config/packages/dev/shq_aws_ses_monitor.yaml` with this content:

```yaml
# Aws Ses Monitor
shq_aws_ses_monitor:
    bounces:
        topic:
            endpoint:
                protocol: '%env(NGROK_APP_SCHEME)%'
                host: '%env(NGROK_APP_HOST)%'
    complaints:
        topic:
            endpoint:
                protocol: '%env(NGROK_APP_SCHEME)%'
                host: '%env(NGROK_APP_HOST)%'
    deliveries:
        topic:
            endpoint:
                protocol: '%env(NGROK_APP_SCHEME)%'
                host: '%env(NGROK_APP_HOST)%'

```

- [x] Add those variables to `.env` file:
    - `NGROK_APP_SCHEME`
    - `NGROK_APP_HOST`
    - `AWS_SES_VERSION`
    - `AWS_SES_TOPIC_BOUNCES`
    - `AWS_SES_TOPIC_COMPLAINTS`
    - `AWS_SES_TOPIC_DELIVERIES`

Other variables used, but not only by AwsSesMonitorBundle
    - `AWS_SNS_VERSION`
    - `AWS_ACCESS_KEY_ID`
    - `AWS_ACCESS_KEY_SECRET`
    - `AWS_REGION`

As on
- https://github.com/Aerendir/stripe-bundle/issues/20
- https://github.com/Aerendir/bundle-commands-queues/issues/39
