### ISSUE TITLE
Only allow to configure the scheme and host for the endpoint

### ISSUE THREAD

**Issue by Aerendir** [Aerendir/bundle-aws-ses-monitor#30]
Currently the bundle requires a configuration like this:

```yaml
# Aws Ses Monitor
shq_aws_ses_monitor:
    aws_config:
        credentials_service_name: 'Aws\Credentials\Credentials'
        region: '%env(AWS_REGION)%'
    bounces:
        topic:
            name: '%env(AWS_SES_TOPIC_BOUNCES)%'
            endpoint:
                protocol: '%env(APP_SCHEME)%'
                host: '%env(APP_HOST)%'
    complaints:
        topic:
            name: '%env(AWS_SES_TOPIC_COMPLAINTS)%'
            endpoint:
                protocol: '%env(APP_SCHEME)%'
                host: '%env(APP_HOST)%'
    deliveries:
        topic:
            name: '%env(AWS_SES_TOPIC_DELIVERIES)%'
            endpoint:
                protocol: '%env(APP_SCHEME)%'
                host: '%env(APP_HOST)%'
```

This is verbose and not useful.

Maybe a configuration like this is better:

```yaml
# Aws Ses Monitor
shq_aws_ses_monitor:
    aws_config:
        credentials_service_name: 'Aws\Credentials\Credentials'
        region: '%env(AWS_REGION)%'
    topics:
        endpoint:
            protocol: '%env(APP_SCHEME)%'
            host: '%env(APP_HOST)%'
    bounces:
        # Remove
        topic:
            name: '%env(AWS_SES_TOPIC_BOUNCES)%'
    complaints:
        # Remove
        topic:
            name: '%env(AWS_SES_TOPIC_COMPLAINTS)%'
    deliveries:
        # Remove
        topic:
            name: '%env(AWS_SES_TOPIC_DELIVERIES)%'
            endpoint:
                protocol: '%env(APP__OTHER_SCHEME)%'
                host: '%env(APP_OTHER_HOST)%'
```

This way is the configuration is way more simple.
