### ISSUE TITLE
Manage identities in configuration

### ISSUE THREAD

**Issue by Aerendir** [Aerendir/bundle-aws-ses-monitor#82]
In configuration is required the management of identities.

```yaml
# Aws Ses Monitor
shq_aws_ses_monitor:
    endpoint:
        scheme: '%env(APP_SCHEME)%'
        host: '%env(APP_HOST)%'
    bounces:
       topic: 'tbme-prod-ses-bounces'
    complaints:
        topic: 'tbme-prod-ses-complaints'
    deliveries:
        topic: 'tbme-prod-ses-deliveries'
```

This is required to configure the identities and the SNS endpoints and to perform the checks and debugging, too

It is possible I want to handle more than one domain from another domain: think at a situation like you build an app on domain `internalmailerapp.com` that manages emails for domain `app1.com` and `app2.com`: they both send emails through internalmyapp.com that is, definitely, a mail server built by yourself.

Considering this, the bundle has to know which identities it is authorized to manage:

```yaml
# Aws Ses Monitor
shq_aws_ses_monitor:
    endpoint:
        scheme: '%env(APP_SCHEME)%'
        host: '%env(APP_HOST)%'
    identities:
        - internalmailerapp.com: ~
        - app1.com: ~
        - app2.com: ~
```

With this configuration the bundle has to be able to configure the identities and to link them to SNS, creating the topics, confirming them, ecc...

In consequence of this, I need to be able to set the bounces, complaints and deliveries topics on a per identity basis.

The identities can be a domain or a single email.

Consider this SES identities:

- www.app1.com
  - hello@app.com
  - support@app1.com
  - test@app1.com

Now, these are the considerations that come from this configuration:

- [x] **The test email** should be used only in `dev`
- [x] **All the identities but the `test@*`** should be configured and used only when in production (instead, the risk is to set a development topic - that maybe uses ngrok - and lose production notifications)
- [x] **The test email** should have its own topic so it is possible to test locally without risking of losing production emails
- [x] **All the identities but the `test@*`** can have the same topic to which deliver the notifications
- [x] The endpoint can be the same for more than one topic
- [x] I can have different topics for different notifications of different identities, but the endpoint MUST be always the same
- [x] The value of `endpoint.host` can be different from the domain of an identity
- [x] The bundle can automatically generate the names of topics
- [x] The bundle can use the name of a topic of domain identity also with the emails that have that same  domain

All this considered, the new configuration should have this shape:

```yaml
# Aws Ses Monitor
shq_aws_ses_monitor:
    endpoint:
        scheme: '%env(APP_SCHEME)%'
        host: '%env(APP_HOST)%'
    identities:
        trustback.me:
            # https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-email-2010-12-01.html#setidentitydkimenabled
            dkim: true
            # https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-email-2010-12-01.html#setidentityfeedbackforwardingenabled
            feedback_forwarding: true
            # https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-email-2010-12-01.html#setidentityheadersinnotificationsenabled
            headers_in_notification: true
            # https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-email-2010-12-01.html#setidentitymailfromdomain
            from_domain: www.trustback.me
            bounces:
                track: true
                topic: 'tbme-prod-ses-bounces' # autogenerated
                filter:
                    enabled: true
                    soft_as_hard: true
                    max_bounces: 5
                    soft_blacklist_time: 'forever'
                    hard_blacklist_time: 'forever'
                    force_send: false
            complaints:
                track: true
                topic: 'tbme-prod-ses-complaints' # autogenerated
                filter:
                    blacklist_time: 'forever'
                    force_send: false
            deliveries:
                track: true
                topic: 'tbme-prod-ses-deliveries' # autogenerated

```
